// The grant protocol: the only cross-environment contract in fiberd.
//
// A control plane (the issuer) signs a CapacityGrant once. A home (a
// standalone host, a Kubernetes grant Pod, a Slurm allocation) verifies it
// offline and mints fibers under it through the Fibers service. Nothing on
// the Clone path calls back to the issuer.
//
// Enum value names follow the plan verbatim (SHED, CREATE, FIBER_WARM, ...)
// rather than buf's prefixed style; buf.yaml excepts those two lint rules.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grant/v1/grant.proto

package grantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fibers_Clone_FullMethodName   = "/fiberd.grant.v1.Fibers/Clone"
	Fibers_Park_FullMethodName    = "/fiberd.grant.v1.Fibers/Park"
	Fibers_Release_FullMethodName = "/fiberd.grant.v1.Fibers/Release"
	Fibers_Watch_FullMethodName   = "/fiberd.grant.v1.Fibers/Watch"
)

// FibersClient is the client API for Fibers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibersClient interface {
	// Clone resolves a session to attach, resume or create. Every miss
	// carries a Miss detail: ResourceExhausted for SHED, Unavailable for
	// DEFERRED_FALLBACK. FailedPrecondition when min_tier exceeds the
	// home's tier or a parked session needs a tier the home lacks.
	Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error)
	Park(ctx context.Context, in *ParkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Watch(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error)
}

type fibersClient struct {
	cc grpc.ClientConnInterface
}

func NewFibersClient(cc grpc.ClientConnInterface) FibersClient {
	return &fibersClient{cc}
}

func (c *fibersClient) Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneResponse)
	err := c.cc.Invoke(ctx, Fibers_Clone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibersClient) Park(ctx context.Context, in *ParkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fibers_Park_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibersClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fibers_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibersClient) Watch(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fibers_ServiceDesc.Streams[0], Fibers_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Status]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fibers_WatchClient = grpc.ServerStreamingClient[Status]

// FibersServer is the server API for Fibers service.
// All implementations must embed UnimplementedFibersServer
// for forward compatibility.
type FibersServer interface {
	// Clone resolves a session to attach, resume or create. Every miss
	// carries a Miss detail: ResourceExhausted for SHED, Unavailable for
	// DEFERRED_FALLBACK. FailedPrecondition when min_tier exceeds the
	// home's tier or a parked session needs a tier the home lacks.
	Clone(context.Context, *CloneRequest) (*CloneResponse, error)
	Park(context.Context, *ParkRequest) (*emptypb.Empty, error)
	Release(context.Context, *ReleaseRequest) (*emptypb.Empty, error)
	Watch(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error
	mustEmbedUnimplementedFibersServer()
}

// UnimplementedFibersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFibersServer struct{}

func (UnimplementedFibersServer) Clone(context.Context, *CloneRequest) (*CloneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedFibersServer) Park(context.Context, *ParkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Park not implemented")
}
func (UnimplementedFibersServer) Release(context.Context, *ReleaseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedFibersServer) Watch(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedFibersServer) mustEmbedUnimplementedFibersServer() {}
func (UnimplementedFibersServer) testEmbeddedByValue()                {}

// UnsafeFibersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibersServer will
// result in compilation errors.
type UnsafeFibersServer interface {
	mustEmbedUnimplementedFibersServer()
}

func RegisterFibersServer(s grpc.ServiceRegistrar, srv FibersServer) {
	// If the following call panics, it indicates UnimplementedFibersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fibers_ServiceDesc, srv)
}

func _Fibers_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibersServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fibers_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibersServer).Clone(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibers_Park_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibersServer).Park(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fibers_Park_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibersServer).Park(ctx, req.(*ParkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibers_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibersServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fibers_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibersServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibers_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FibersServer).Watch(m, &grpc.GenericServerStream[emptypb.Empty, Status]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fibers_WatchServer = grpc.ServerStreamingServer[Status]

// Fibers_ServiceDesc is the grpc.ServiceDesc for Fibers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fibers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fiberd.grant.v1.Fibers",
	HandlerType: (*FibersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Clone",
			Handler:    _Fibers_Clone_Handler,
		},
		{
			MethodName: "Park",
			Handler:    _Fibers_Park_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Fibers_Release_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Fibers_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grant/v1/grant.proto",
}
