// The grant protocol: the only cross-environment contract in fiberd.
//
// A control plane (the issuer) signs a CapacityGrant once. A home (a
// standalone host, a Kubernetes grant Pod, a Slurm allocation) verifies it
// offline and mints fibers under it through the Fibers service. Nothing on
// the Clone path calls back to the issuer.
//
// Enum value names follow the plan verbatim (SHED, CREATE, FIBER_WARM, ...)
// rather than buf's prefixed style; buf.yaml excepts those two lint rules.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grant/v1/grant.proto

package grantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tier is the runtime capability a home advertises and a grant demands.
// A grant with min_tier above the home's tier is never satisfied by a
// lesser mechanism: Clone fails with FailedPrecondition, never a fresh fork.
type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	// Create a worker in an existing warm sandbox. Correct semantics,
	// pod-class latency. Every runtime qualifies.
	Tier_FIBER_BASIC Tier = 1
	// Zygote fork, copy-on-write. Millisecond activation and density.
	// Single-tenant per grant by definition.
	Tier_FIBER_WARM Tier = 2
	// Per-fiber delta checkpoint and restore. Park/resume, the session model.
	Tier_FIBER_CHECKPOINT Tier = 3
	// MicroVM or gVisor snapshot-restore per fiber. Multi-tenant per node.
	Tier_FIBER_SNAPSHOT Tier = 4
	// Reserved. Multi-node fabric tier; nothing implements it.
	Tier_FIBER_FABRIC Tier = 5
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "FIBER_BASIC",
		2: "FIBER_WARM",
		3: "FIBER_CHECKPOINT",
		4: "FIBER_SNAPSHOT",
		5: "FIBER_FABRIC",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"FIBER_BASIC":      1,
		"FIBER_WARM":       2,
		"FIBER_CHECKPOINT": 3,
		"FIBER_SNAPSHOT":   4,
		"FIBER_FABRIC":     5,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_grant_v1_grant_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_grant_v1_grant_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{0}
}

// Durability selects when the audit record for an operation must be remote.
type Durability int32

const (
	Durability_DURABILITY_UNSPECIFIED Durability = 0
	// Append locally, ack the caller, ship later. Loss window = flush interval.
	Durability_BEST_EFFORT Durability = 1
	// Block until the record is remote, then ack. Paid as activation latency.
	Durability_SYNC Durability = 2
)

// Enum value maps for Durability.
var (
	Durability_name = map[int32]string{
		0: "DURABILITY_UNSPECIFIED",
		1: "BEST_EFFORT",
		2: "SYNC",
	}
	Durability_value = map[string]int32{
		"DURABILITY_UNSPECIFIED": 0,
		"BEST_EFFORT":            1,
		"SYNC":                   2,
	}
)

func (x Durability) Enum() *Durability {
	p := new(Durability)
	*p = x
	return p
}

func (x Durability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Durability) Descriptor() protoreflect.EnumDescriptor {
	return file_grant_v1_grant_proto_enumTypes[1].Descriptor()
}

func (Durability) Type() protoreflect.EnumType {
	return &file_grant_v1_grant_proto_enumTypes[1]
}

func (x Durability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Durability.Descriptor instead.
func (Durability) EnumDescriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{1}
}

type CloneKind int32

const (
	CloneKind_CREATE CloneKind = 0
	CloneKind_ATTACH CloneKind = 1
	CloneKind_RESUME CloneKind = 2
)

// Enum value maps for CloneKind.
var (
	CloneKind_name = map[int32]string{
		0: "CREATE",
		1: "ATTACH",
		2: "RESUME",
	}
	CloneKind_value = map[string]int32{
		"CREATE": 0,
		"ATTACH": 1,
		"RESUME": 2,
	}
)

func (x CloneKind) Enum() *CloneKind {
	p := new(CloneKind)
	*p = x
	return p
}

func (x CloneKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloneKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grant_v1_grant_proto_enumTypes[2].Descriptor()
}

func (CloneKind) Type() protoreflect.EnumType {
	return &file_grant_v1_grant_proto_enumTypes[2]
}

func (x CloneKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloneKind.Descriptor instead.
func (CloneKind) EnumDescriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{2}
}

// MissCode is the one thing a caller needs to decide what to do next.
type MissCode int32

const (
	// The control plane is unreachable or the thrash budget is exceeded.
	// Back off for retry_after_s; never queue on a dead control plane.
	MissCode_SHED MissCode = 0
	// Capacity is not on this home and the control plane is healthy.
	// Fall back to the home's ordinary provisioning path.
	MissCode_DEFERRED_FALLBACK MissCode = 1
)

// Enum value maps for MissCode.
var (
	MissCode_name = map[int32]string{
		0: "SHED",
		1: "DEFERRED_FALLBACK",
	}
	MissCode_value = map[string]int32{
		"SHED":              0,
		"DEFERRED_FALLBACK": 1,
	}
)

func (x MissCode) Enum() *MissCode {
	p := new(MissCode)
	*p = x
	return p
}

func (x MissCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grant_v1_grant_proto_enumTypes[3].Descriptor()
}

func (MissCode) Type() protoreflect.EnumType {
	return &file_grant_v1_grant_proto_enumTypes[3]
}

func (x MissCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissCode.Descriptor instead.
func (MissCode) EnumDescriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{3}
}

// Policy is the per-grant session, durability and pressure class.
type Policy struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Durability   Durability             `protobuf:"varint,1,opt,name=durability,proto3,enum=fiberd.grant.v1.Durability" json:"durability,omitempty"`
	SessionClass string                 `protobuf:"bytes,2,opt,name=session_class,json=sessionClass,proto3" json:"session_class,omitempty"`
	AuditClass   string                 `protobuf:"bytes,3,opt,name=audit_class,json=auditClass,proto3" json:"audit_class,omitempty"`
	// PSI memory "some avg10" watermarks on the grant's cgroup, in percent.
	// The home sets them below its own eviction threshold so park fires first.
	PsiSomeAvg10Shed float32 `protobuf:"fixed32,4,opt,name=psi_some_avg10_shed,json=psiSomeAvg10Shed,proto3" json:"psi_some_avg10_shed,omitempty"`
	PsiSomeAvg10Park float32 `protobuf:"fixed32,5,opt,name=psi_some_avg10_park,json=psiSomeAvg10Park,proto3" json:"psi_some_avg10_park,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_grant_v1_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetDurability() Durability {
	if x != nil {
		return x.Durability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

func (x *Policy) GetSessionClass() string {
	if x != nil {
		return x.SessionClass
	}
	return ""
}

func (x *Policy) GetAuditClass() string {
	if x != nil {
		return x.AuditClass
	}
	return ""
}

func (x *Policy) GetPsiSomeAvg10Shed() float32 {
	if x != nil {
		return x.PsiSomeAvg10Shed
	}
	return 0
}

func (x *Policy) GetPsiSomeAvg10Park() float32 {
	if x != nil {
		return x.PsiSomeAvg10Park
	}
	return 0
}

// FiberLimits is `fibers: {max, warm}`. (Named FiberLimits rather than
// Fibers because the service below already takes that name.)
type FiberLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           uint32                 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Warm          uint32                 `protobuf:"varint,2,opt,name=warm,proto3" json:"warm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiberLimits) Reset() {
	*x = FiberLimits{}
	mi := &file_grant_v1_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiberLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiberLimits) ProtoMessage() {}

func (x *FiberLimits) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiberLimits.ProtoReflect.Descriptor instead.
func (*FiberLimits) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{1}
}

func (x *FiberLimits) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *FiberLimits) GetWarm() uint32 {
	if x != nil {
		return x.Warm
	}
	return 0
}

// DeviceBudget is the per-fiber slice of the engine's device state (its
// KV cache, its VRAM) a fiber may hold: the device-side twin of
// w_budget_bytes. On the GPU side one engine per grant owns the device
// and fibers are its clients; the engine reports each fiber's slice and
// the home enforces this budget on the report, since the kernel has no
// pressure class for devices. A home whose template offers no device of
// this class refuses the grant with FailedPrecondition, never a silent
// CPU-only fiber.
type DeviceBudget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Bytes uint64                 `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// class names the device the budget is for ("gpu"; "sim" is the
	// reference workload's simulated engine). Empty means any.
	Class         string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceBudget) Reset() {
	*x = DeviceBudget{}
	mi := &file_grant_v1_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBudget) ProtoMessage() {}

func (x *DeviceBudget) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBudget.ProtoReflect.Descriptor instead.
func (*DeviceBudget) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceBudget) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *DeviceBudget) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

// CapacityGrant is what the issuer signs. It is carried as the `grant`
// claim of a JWT whose registered claims mirror issuer, audience,
// lease_expiry and grant_uid (iss, aud, exp, jti).
type CapacityGrant struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GrantUid string                 `protobuf:"bytes,1,opt,name=grant_uid,json=grantUid,proto3" json:"grant_uid,omitempty"`
	// OIDC issuer URL of the issuing home. Verifiers discover the JWKS here.
	Issuer string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Target environment id: the home that may exercise this grant.
	Audience string `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	// OCI digest of the zygote artifact, or of the template image.
	TemplateDigest string       `protobuf:"bytes,4,opt,name=template_digest,json=templateDigest,proto3" json:"template_digest,omitempty"`
	Fibers         *FiberLimits `protobuf:"bytes,5,opt,name=fibers,proto3" json:"fibers,omitempty"`
	// Maximum dirtied working set per fiber, in bytes. Enforced as the
	// fiber's cgroup memory.max; also the mobility budget for deltas.
	WBudgetBytes uint64                 `protobuf:"varint,6,opt,name=w_budget_bytes,json=wBudgetBytes,proto3" json:"w_budget_bytes,omitempty"`
	MinTier      Tier                   `protobuf:"varint,7,opt,name=min_tier,json=minTier,proto3,enum=fiberd.grant.v1.Tier" json:"min_tier,omitempty"`
	LeaseExpiry  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lease_expiry,json=leaseExpiry,proto3" json:"lease_expiry,omitempty"`
	Policy       *Policy                `protobuf:"bytes,9,opt,name=policy,proto3" json:"policy,omitempty"`
	// Absent or zero bytes: the grant needs no device.
	DeviceBudget  *DeviceBudget `protobuf:"bytes,10,opt,name=device_budget,json=deviceBudget,proto3" json:"device_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityGrant) Reset() {
	*x = CapacityGrant{}
	mi := &file_grant_v1_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityGrant) ProtoMessage() {}

func (x *CapacityGrant) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityGrant.ProtoReflect.Descriptor instead.
func (*CapacityGrant) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{3}
}

func (x *CapacityGrant) GetGrantUid() string {
	if x != nil {
		return x.GrantUid
	}
	return ""
}

func (x *CapacityGrant) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CapacityGrant) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *CapacityGrant) GetTemplateDigest() string {
	if x != nil {
		return x.TemplateDigest
	}
	return ""
}

func (x *CapacityGrant) GetFibers() *FiberLimits {
	if x != nil {
		return x.Fibers
	}
	return nil
}

func (x *CapacityGrant) GetWBudgetBytes() uint64 {
	if x != nil {
		return x.WBudgetBytes
	}
	return 0
}

func (x *CapacityGrant) GetMinTier() Tier {
	if x != nil {
		return x.MinTier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *CapacityGrant) GetLeaseExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiry
	}
	return nil
}

func (x *CapacityGrant) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CapacityGrant) GetDeviceBudget() *DeviceBudget {
	if x != nil {
		return x.DeviceBudget
	}
	return nil
}

// Fence identifies one incarnation of a fiber: (grant, agent epoch, seq).
// Every credential and claim is scoped to it. An epoch bump on agent
// restart invalidates every prior fence at once.
type Fence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantUid      string                 `protobuf:"bytes,1,opt,name=grant_uid,json=grantUid,proto3" json:"grant_uid,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fence) Reset() {
	*x = Fence{}
	mi := &file_grant_v1_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fence) ProtoMessage() {}

func (x *Fence) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fence.ProtoReflect.Descriptor instead.
func (*Fence) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{4}
}

func (x *Fence) GetGrantUid() string {
	if x != nil {
		return x.GrantUid
	}
	return ""
}

func (x *Fence) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Fence) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// CloneRequest is the entire clone-time surface. Admission completeness is
// structural: there is no field with which to shape a workload. A request
// carrying any other field is rejected with InvalidArgument.
type CloneRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GrantJwt string                 `protobuf:"bytes,1,opt,name=grant_jwt,json=grantJwt,proto3" json:"grant_jwt,omitempty"`
	// Optional stable identity. Empty means an anonymous, fungible fiber.
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// Hard budget for the runtime work; exceeding it is a miss, not a late fiber.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Opaque, size-capped (4096 bytes), delivered as data, never config.
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_grant_v1_grant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{5}
}

func (x *CloneRequest) GetGrantJwt() string {
	if x != nil {
		return x.GrantJwt
	}
	return ""
}

func (x *CloneRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CloneRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CloneRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FiberId       string                 `protobuf:"bytes,1,opt,name=fiber_id,json=fiberId,proto3" json:"fiber_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Fence         *Fence                 `protobuf:"bytes,3,opt,name=fence,proto3" json:"fence,omitempty"`
	Kind          CloneKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=fiberd.grant.v1.CloneKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_grant_v1_grant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{6}
}

func (x *CloneResponse) GetFiberId() string {
	if x != nil {
		return x.FiberId
	}
	return ""
}

func (x *CloneResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CloneResponse) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *CloneResponse) GetKind() CloneKind {
	if x != nil {
		return x.Kind
	}
	return CloneKind_CREATE
}

// Miss is attached to every miss error as a google.rpc.Status detail.
type Miss struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Code        MissCode               `protobuf:"varint,1,opt,name=code,proto3,enum=fiberd.grant.v1.MissCode" json:"code,omitempty"`
	RetryAfterS uint32                 `protobuf:"varint,2,opt,name=retry_after_s,json=retryAfterS,proto3" json:"retry_after_s,omitempty"`
	Issuer      string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// For DEFERRED_FALLBACK: the home that holds the session's parked
	// state, when known.
	PreferredHome string `protobuf:"bytes,4,opt,name=preferred_home,json=preferredHome,proto3" json:"preferred_home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Miss) Reset() {
	*x = Miss{}
	mi := &file_grant_v1_grant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Miss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Miss) ProtoMessage() {}

func (x *Miss) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Miss.ProtoReflect.Descriptor instead.
func (*Miss) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{7}
}

func (x *Miss) GetCode() MissCode {
	if x != nil {
		return x.Code
	}
	return MissCode_SHED
}

func (x *Miss) GetRetryAfterS() uint32 {
	if x != nil {
		return x.RetryAfterS
	}
	return 0
}

func (x *Miss) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Miss) GetPreferredHome() string {
	if x != nil {
		return x.PreferredHome
	}
	return ""
}

type ParkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FiberId string                 `protobuf:"bytes,1,opt,name=fiber_id,json=fiberId,proto3" json:"fiber_id,omitempty"`
	// sync: checkpoint completes before the reply; the fiber keeps running
	// until the delta is durable.
	Sync          bool `protobuf:"varint,2,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkRequest) Reset() {
	*x = ParkRequest{}
	mi := &file_grant_v1_grant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkRequest) ProtoMessage() {}

func (x *ParkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkRequest.ProtoReflect.Descriptor instead.
func (*ParkRequest) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{8}
}

func (x *ParkRequest) GetFiberId() string {
	if x != nil {
		return x.FiberId
	}
	return ""
}

func (x *ParkRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type ReleaseRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FiberId string                 `protobuf:"bytes,1,opt,name=fiber_id,json=fiberId,proto3" json:"fiber_id,omitempty"`
	// discard: also delete any parked delta for the fiber's session.
	Discard       bool `protobuf:"varint,2,opt,name=discard,proto3" json:"discard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_grant_v1_grant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseRequest) GetFiberId() string {
	if x != nil {
		return x.FiberId
	}
	return ""
}

func (x *ReleaseRequest) GetDiscard() bool {
	if x != nil {
		return x.Discard
	}
	return false
}

// Status is the batched, per-grant view the home publishes. It is the
// only thing a control plane ever sees; never individual fibers.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantUid      string                 `protobuf:"bytes,1,opt,name=grant_uid,json=grantUid,proto3" json:"grant_uid,omitempty"`
	Running       uint32                 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Parked        uint32                 `protobuf:"varint,3,opt,name=parked,proto3" json:"parked,omitempty"`
	WUsedBytes    uint64                 `protobuf:"varint,4,opt,name=w_used_bytes,json=wUsedBytes,proto3" json:"w_used_bytes,omitempty"`
	Latest        *Fence                 `protobuf:"bytes,5,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_grant_v1_grant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_grant_v1_grant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_grant_v1_grant_proto_rawDescGZIP(), []int{10}
}

func (x *Status) GetGrantUid() string {
	if x != nil {
		return x.GrantUid
	}
	return ""
}

func (x *Status) GetRunning() uint32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *Status) GetParked() uint32 {
	if x != nil {
		return x.Parked
	}
	return 0
}

func (x *Status) GetWUsedBytes() uint64 {
	if x != nil {
		return x.WUsedBytes
	}
	return 0
}

func (x *Status) GetLatest() *Fence {
	if x != nil {
		return x.Latest
	}
	return nil
}

var File_grant_v1_grant_proto protoreflect.FileDescriptor

const file_grant_v1_grant_proto_rawDesc = "" +
	"\n" +
	"\x14grant/v1/grant.proto\x12\x0ffiberd.grant.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\x06Policy\x12;\n" +
	"\n" +
	"durability\x18\x01 \x01(\x0e2\x1b.fiberd.grant.v1.DurabilityR\n" +
	"durability\x12#\n" +
	"\rsession_class\x18\x02 \x01(\tR\fsessionClass\x12\x1f\n" +
	"\vaudit_class\x18\x03 \x01(\tR\n" +
	"auditClass\x12-\n" +
	"\x13psi_some_avg10_shed\x18\x04 \x01(\x02R\x10psiSomeAvg10Shed\x12-\n" +
	"\x13psi_some_avg10_park\x18\x05 \x01(\x02R\x10psiSomeAvg10Park\"3\n" +
	"\vFiberLimits\x12\x10\n" +
	"\x03max\x18\x01 \x01(\rR\x03max\x12\x12\n" +
	"\x04warm\x18\x02 \x01(\rR\x04warm\":\n" +
	"\fDeviceBudget\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\x04R\x05bytes\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\"\xcb\x03\n" +
	"\rCapacityGrant\x12\x1b\n" +
	"\tgrant_uid\x18\x01 \x01(\tR\bgrantUid\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\x12'\n" +
	"\x0ftemplate_digest\x18\x04 \x01(\tR\x0etemplateDigest\x124\n" +
	"\x06fibers\x18\x05 \x01(\v2\x1c.fiberd.grant.v1.FiberLimitsR\x06fibers\x12$\n" +
	"\x0ew_budget_bytes\x18\x06 \x01(\x04R\fwBudgetBytes\x120\n" +
	"\bmin_tier\x18\a \x01(\x0e2\x15.fiberd.grant.v1.TierR\aminTier\x12=\n" +
	"\flease_expiry\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vleaseExpiry\x12/\n" +
	"\x06policy\x18\t \x01(\v2\x17.fiberd.grant.v1.PolicyR\x06policy\x12B\n" +
	"\rdevice_budget\x18\n" +
	" \x01(\v2\x1d.fiberd.grant.v1.DeviceBudgetR\fdeviceBudget\"L\n" +
	"\x05Fence\x12\x1b\n" +
	"\tgrant_uid\x18\x01 \x01(\tR\bgrantUid\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x97\x01\n" +
	"\fCloneRequest\x12\x1b\n" +
	"\tgrant_jwt\x18\x01 \x01(\tR\bgrantJwt\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xa4\x01\n" +
	"\rCloneResponse\x12\x19\n" +
	"\bfiber_id\x18\x01 \x01(\tR\afiberId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12,\n" +
	"\x05fence\x18\x03 \x01(\v2\x16.fiberd.grant.v1.FenceR\x05fence\x12.\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1a.fiberd.grant.v1.CloneKindR\x04kind\"\x98\x01\n" +
	"\x04Miss\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.fiberd.grant.v1.MissCodeR\x04code\x12\"\n" +
	"\rretry_after_s\x18\x02 \x01(\rR\vretryAfterS\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12%\n" +
	"\x0epreferred_home\x18\x04 \x01(\tR\rpreferredHome\"<\n" +
	"\vParkRequest\x12\x19\n" +
	"\bfiber_id\x18\x01 \x01(\tR\afiberId\x12\x12\n" +
	"\x04sync\x18\x02 \x01(\bR\x04sync\"E\n" +
	"\x0eReleaseRequest\x12\x19\n" +
	"\bfiber_id\x18\x01 \x01(\tR\afiberId\x12\x18\n" +
	"\adiscard\x18\x02 \x01(\bR\adiscard\"\xa9\x01\n" +
	"\x06Status\x12\x1b\n" +
	"\tgrant_uid\x18\x01 \x01(\tR\bgrantUid\x12\x18\n" +
	"\arunning\x18\x02 \x01(\rR\arunning\x12\x16\n" +
	"\x06parked\x18\x03 \x01(\rR\x06parked\x12 \n" +
	"\fw_used_bytes\x18\x04 \x01(\x04R\n" +
	"wUsedBytes\x12.\n" +
	"\x06latest\x18\x05 \x01(\v2\x16.fiberd.grant.v1.FenceR\x06latest*y\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vFIBER_BASIC\x10\x01\x12\x0e\n" +
	"\n" +
	"FIBER_WARM\x10\x02\x12\x14\n" +
	"\x10FIBER_CHECKPOINT\x10\x03\x12\x12\n" +
	"\x0eFIBER_SNAPSHOT\x10\x04\x12\x10\n" +
	"\fFIBER_FABRIC\x10\x05*C\n" +
	"\n" +
	"Durability\x12\x1a\n" +
	"\x16DURABILITY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vBEST_EFFORT\x10\x01\x12\b\n" +
	"\x04SYNC\x10\x02*/\n" +
	"\tCloneKind\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06ATTACH\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02*+\n" +
	"\bMissCode\x12\b\n" +
	"\x04SHED\x10\x00\x12\x15\n" +
	"\x11DEFERRED_FALLBACK\x10\x012\x8e\x02\n" +
	"\x06Fibers\x12F\n" +
	"\x05Clone\x12\x1d.fiberd.grant.v1.CloneRequest\x1a\x1e.fiberd.grant.v1.CloneResponse\x12<\n" +
	"\x04Park\x12\x1c.fiberd.grant.v1.ParkRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\aRelease\x12\x1f.fiberd.grant.v1.ReleaseRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x05Watch\x12\x16.google.protobuf.Empty\x1a\x17.fiberd.grant.v1.Status0\x01B1Z/github.com/helayoty/fiberd/api/grant/v1;grantv1b\x06proto3"

var (
	file_grant_v1_grant_proto_rawDescOnce sync.Once
	file_grant_v1_grant_proto_rawDescData []byte
)

func file_grant_v1_grant_proto_rawDescGZIP() []byte {
	file_grant_v1_grant_proto_rawDescOnce.Do(func() {
		file_grant_v1_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grant_v1_grant_proto_rawDesc), len(file_grant_v1_grant_proto_rawDesc)))
	})
	return file_grant_v1_grant_proto_rawDescData
}

var file_grant_v1_grant_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_grant_v1_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grant_v1_grant_proto_goTypes = []any{
	(Tier)(0),                     // 0: fiberd.grant.v1.Tier
	(Durability)(0),               // 1: fiberd.grant.v1.Durability
	(CloneKind)(0),                // 2: fiberd.grant.v1.CloneKind
	(MissCode)(0),                 // 3: fiberd.grant.v1.MissCode
	(*Policy)(nil),                // 4: fiberd.grant.v1.Policy
	(*FiberLimits)(nil),           // 5: fiberd.grant.v1.FiberLimits
	(*DeviceBudget)(nil),          // 6: fiberd.grant.v1.DeviceBudget
	(*CapacityGrant)(nil),         // 7: fiberd.grant.v1.CapacityGrant
	(*Fence)(nil),                 // 8: fiberd.grant.v1.Fence
	(*CloneRequest)(nil),          // 9: fiberd.grant.v1.CloneRequest
	(*CloneResponse)(nil),         // 10: fiberd.grant.v1.CloneResponse
	(*Miss)(nil),                  // 11: fiberd.grant.v1.Miss
	(*ParkRequest)(nil),           // 12: fiberd.grant.v1.ParkRequest
	(*ReleaseRequest)(nil),        // 13: fiberd.grant.v1.ReleaseRequest
	(*Status)(nil),                // 14: fiberd.grant.v1.Status
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_grant_v1_grant_proto_depIdxs = []int32{
	1,  // 0: fiberd.grant.v1.Policy.durability:type_name -> fiberd.grant.v1.Durability
	5,  // 1: fiberd.grant.v1.CapacityGrant.fibers:type_name -> fiberd.grant.v1.FiberLimits
	0,  // 2: fiberd.grant.v1.CapacityGrant.min_tier:type_name -> fiberd.grant.v1.Tier
	15, // 3: fiberd.grant.v1.CapacityGrant.lease_expiry:type_name -> google.protobuf.Timestamp
	4,  // 4: fiberd.grant.v1.CapacityGrant.policy:type_name -> fiberd.grant.v1.Policy
	6,  // 5: fiberd.grant.v1.CapacityGrant.device_budget:type_name -> fiberd.grant.v1.DeviceBudget
	15, // 6: fiberd.grant.v1.CloneRequest.deadline:type_name -> google.protobuf.Timestamp
	8,  // 7: fiberd.grant.v1.CloneResponse.fence:type_name -> fiberd.grant.v1.Fence
	2,  // 8: fiberd.grant.v1.CloneResponse.kind:type_name -> fiberd.grant.v1.CloneKind
	3,  // 9: fiberd.grant.v1.Miss.code:type_name -> fiberd.grant.v1.MissCode
	8,  // 10: fiberd.grant.v1.Status.latest:type_name -> fiberd.grant.v1.Fence
	9,  // 11: fiberd.grant.v1.Fibers.Clone:input_type -> fiberd.grant.v1.CloneRequest
	12, // 12: fiberd.grant.v1.Fibers.Park:input_type -> fiberd.grant.v1.ParkRequest
	13, // 13: fiberd.grant.v1.Fibers.Release:input_type -> fiberd.grant.v1.ReleaseRequest
	16, // 14: fiberd.grant.v1.Fibers.Watch:input_type -> google.protobuf.Empty
	10, // 15: fiberd.grant.v1.Fibers.Clone:output_type -> fiberd.grant.v1.CloneResponse
	16, // 16: fiberd.grant.v1.Fibers.Park:output_type -> google.protobuf.Empty
	16, // 17: fiberd.grant.v1.Fibers.Release:output_type -> google.protobuf.Empty
	14, // 18: fiberd.grant.v1.Fibers.Watch:output_type -> fiberd.grant.v1.Status
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_grant_v1_grant_proto_init() }
func file_grant_v1_grant_proto_init() {
	if File_grant_v1_grant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grant_v1_grant_proto_rawDesc), len(file_grant_v1_grant_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grant_v1_grant_proto_goTypes,
		DependencyIndexes: file_grant_v1_grant_proto_depIdxs,
		EnumInfos:         file_grant_v1_grant_proto_enumTypes,
		MessageInfos:      file_grant_v1_grant_proto_msgTypes,
	}.Build()
	File_grant_v1_grant_proto = out.File
	file_grant_v1_grant_proto_goTypes = nil
	file_grant_v1_grant_proto_depIdxs = nil
}
