// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: atelet/atelet.proto

package ateletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetWorkerCapacityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the worker can supply, in the same vocabulary the control plane
	// records and an ActorTemplate asks in.
	Capacity      *WorkerResources `protobuf:"bytes,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkerCapacityRequest) Reset() {
	*x = SetWorkerCapacityRequest{}
	mi := &file_atelet_atelet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkerCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkerCapacityRequest) ProtoMessage() {}

func (x *SetWorkerCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_atelet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkerCapacityRequest.ProtoReflect.Descriptor instead.
func (*SetWorkerCapacityRequest) Descriptor() ([]byte, []int) {
	return file_atelet_atelet_proto_rawDescGZIP(), []int{0}
}

func (x *SetWorkerCapacityRequest) GetCapacity() *WorkerResources {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type SetWorkerCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkerCapacityResponse) Reset() {
	*x = SetWorkerCapacityResponse{}
	mi := &file_atelet_atelet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkerCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkerCapacityResponse) ProtoMessage() {}

func (x *SetWorkerCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_atelet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkerCapacityResponse.ProtoReflect.Descriptor instead.
func (*SetWorkerCapacityResponse) Descriptor() ([]byte, []int) {
	return file_atelet_atelet_proto_rawDescGZIP(), []int{1}
}

// ateapi.WorkerResources.
type WorkerResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resources match the Actor's definition of resources.
	// They are matched by name and used for placement.
	Resources *Resources `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	// A count of Actors.  Workers can use this to limit the number of Actors
	// that can be placed on them, constraining the costs of other things that
	// are not captured in the resources above, but which still have costs -
	// netns, mounts, file descriptors, etc.
	Actors        int32 `protobuf:"varint,2,opt,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResources) Reset() {
	*x = WorkerResources{}
	mi := &file_atelet_atelet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResources) ProtoMessage() {}

func (x *WorkerResources) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_atelet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResources.ProtoReflect.Descriptor instead.
func (*WorkerResources) Descriptor() ([]byte, []int) {
	return file_atelet_atelet_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerResources) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkerResources) GetActors() int32 {
	if x != nil {
		return x.Actors
	}
	return 0
}

// ateapi.Resources.
type Resources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limits is the maximum amount of compute resources allowed. Only "cpu"
	// and "memory" are supported, each at most once, and each quantity must be
	// greater than zero; the cpu limit must be less than 1000 cores.
	Limits        []*Limits `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_atelet_atelet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_atelet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_atelet_atelet_proto_rawDescGZIP(), []int{3}
}

func (x *Resources) GetLimits() []*Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// ateapi.Limits.
type Limits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// quantity is in Kubernetes resource.Quantity string form (e.g. "500m",
	// "2Gi").
	Quantity      string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_atelet_atelet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_atelet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_atelet_atelet_proto_rawDescGZIP(), []int{4}
}

func (x *Limits) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Limits) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

var File_atelet_atelet_proto protoreflect.FileDescriptor

const file_atelet_atelet_proto_rawDesc = "" +
	"\n" +
	"\x13atelet/atelet.proto\x12\x06atelet\"O\n" +
	"\x18SetWorkerCapacityRequest\x123\n" +
	"\bcapacity\x18\x01 \x01(\v2\x17.atelet.WorkerResourcesR\bcapacity\"\x1b\n" +
	"\x19SetWorkerCapacityResponse\"Z\n" +
	"\x0fWorkerResources\x12/\n" +
	"\tresources\x18\x01 \x01(\v2\x11.atelet.ResourcesR\tresources\x12\x16\n" +
	"\x06actors\x18\x02 \x01(\x05R\x06actors\"3\n" +
	"\tResources\x12&\n" +
	"\x06limits\x18\x01 \x03(\v2\x0e.atelet.LimitsR\x06limits\"8\n" +
	"\x06Limits\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity2j\n" +
	"\fAteomSupport\x12Z\n" +
	"\x11SetWorkerCapacity\x12 .atelet.SetWorkerCapacityRequest\x1a!.atelet.SetWorkerCapacityResponse\"\x00BEZCgithub.com/helayoty/fiberd/examples/substrate/proto/atelet;ateletpbb\x06proto3"

var (
	file_atelet_atelet_proto_rawDescOnce sync.Once
	file_atelet_atelet_proto_rawDescData []byte
)

func file_atelet_atelet_proto_rawDescGZIP() []byte {
	file_atelet_atelet_proto_rawDescOnce.Do(func() {
		file_atelet_atelet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atelet_atelet_proto_rawDesc), len(file_atelet_atelet_proto_rawDesc)))
	})
	return file_atelet_atelet_proto_rawDescData
}

var file_atelet_atelet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_atelet_atelet_proto_goTypes = []any{
	(*SetWorkerCapacityRequest)(nil),  // 0: atelet.SetWorkerCapacityRequest
	(*SetWorkerCapacityResponse)(nil), // 1: atelet.SetWorkerCapacityResponse
	(*WorkerResources)(nil),           // 2: atelet.WorkerResources
	(*Resources)(nil),                 // 3: atelet.Resources
	(*Limits)(nil),                    // 4: atelet.Limits
}
var file_atelet_atelet_proto_depIdxs = []int32{
	2, // 0: atelet.SetWorkerCapacityRequest.capacity:type_name -> atelet.WorkerResources
	3, // 1: atelet.WorkerResources.resources:type_name -> atelet.Resources
	4, // 2: atelet.Resources.limits:type_name -> atelet.Limits
	0, // 3: atelet.AteomSupport.SetWorkerCapacity:input_type -> atelet.SetWorkerCapacityRequest
	1, // 4: atelet.AteomSupport.SetWorkerCapacity:output_type -> atelet.SetWorkerCapacityResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_atelet_atelet_proto_init() }
func file_atelet_atelet_proto_init() {
	if File_atelet_atelet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atelet_atelet_proto_rawDesc), len(file_atelet_atelet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atelet_atelet_proto_goTypes,
		DependencyIndexes: file_atelet_atelet_proto_depIdxs,
		MessageInfos:      file_atelet_atelet_proto_msgTypes,
	}.Build()
	File_atelet_atelet_proto = out.File
	file_atelet_atelet_proto_goTypes = nil
	file_atelet_atelet_proto_depIdxs = nil
}
