// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: atelet/atelet.proto

package ateletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AteomSupport_SetWorkerCapacity_FullMethodName = "/atelet.AteomSupport/SetWorkerCapacity"
)

// AteomSupportClient is the client API for AteomSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AteomSupport provides callouts for ateom.
//
// Called by individual ateom pods over a local connection, authenticated with
// ateom's k8s pod identity mTLS certificate.
type AteomSupportClient interface {
	// Report capacity and supply for this worker back to atelet.
	SetWorkerCapacity(ctx context.Context, in *SetWorkerCapacityRequest, opts ...grpc.CallOption) (*SetWorkerCapacityResponse, error)
}

type ateomSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewAteomSupportClient(cc grpc.ClientConnInterface) AteomSupportClient {
	return &ateomSupportClient{cc}
}

func (c *ateomSupportClient) SetWorkerCapacity(ctx context.Context, in *SetWorkerCapacityRequest, opts ...grpc.CallOption) (*SetWorkerCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWorkerCapacityResponse)
	err := c.cc.Invoke(ctx, AteomSupport_SetWorkerCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteomSupportServer is the server API for AteomSupport service.
// All implementations must embed UnimplementedAteomSupportServer
// for forward compatibility.
//
// AteomSupport provides callouts for ateom.
//
// Called by individual ateom pods over a local connection, authenticated with
// ateom's k8s pod identity mTLS certificate.
type AteomSupportServer interface {
	// Report capacity and supply for this worker back to atelet.
	SetWorkerCapacity(context.Context, *SetWorkerCapacityRequest) (*SetWorkerCapacityResponse, error)
	mustEmbedUnimplementedAteomSupportServer()
}

// UnimplementedAteomSupportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAteomSupportServer struct{}

func (UnimplementedAteomSupportServer) SetWorkerCapacity(context.Context, *SetWorkerCapacityRequest) (*SetWorkerCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWorkerCapacity not implemented")
}
func (UnimplementedAteomSupportServer) mustEmbedUnimplementedAteomSupportServer() {}
func (UnimplementedAteomSupportServer) testEmbeddedByValue()                      {}

// UnsafeAteomSupportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AteomSupportServer will
// result in compilation errors.
type UnsafeAteomSupportServer interface {
	mustEmbedUnimplementedAteomSupportServer()
}

func RegisterAteomSupportServer(s grpc.ServiceRegistrar, srv AteomSupportServer) {
	// If the following call panics, it indicates UnimplementedAteomSupportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AteomSupport_ServiceDesc, srv)
}

func _AteomSupport_SetWorkerCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWorkerCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomSupportServer).SetWorkerCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomSupport_SetWorkerCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomSupportServer).SetWorkerCapacity(ctx, req.(*SetWorkerCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AteomSupport_ServiceDesc is the grpc.ServiceDesc for AteomSupport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AteomSupport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atelet.AteomSupport",
	HandlerType: (*AteomSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetWorkerCapacity",
			Handler:    _AteomSupport_SetWorkerCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atelet/atelet.proto",
}
